# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = S:\pico\Blink

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = S:\pico\Blink

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start S:\pico\Blink\CMakeFiles S:\pico\Blink\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start S:\pico\Blink\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Button

# Build rule for target.
Button: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Button
.PHONY : Button

# fast build rule for target.
Button/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/build
.PHONY : Button/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ELF2UF2Build.dir\build.make CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default_bin.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default_padded_checksummed_asm.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

P_/pico-sdk/src/common/pico_sync/critical_section.obj: P_/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.obj

# target to build an object file
P_/pico-sdk/src/common/pico_sync/critical_section.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.c.obj

P_/pico-sdk/src/common/pico_sync/critical_section.i: P_/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_sync/critical_section.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.c.i

P_/pico-sdk/src/common/pico_sync/critical_section.s: P_/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_sync/critical_section.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/critical_section.c.s

P_/pico-sdk/src/common/pico_sync/lock_core.obj: P_/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.obj

# target to build an object file
P_/pico-sdk/src/common/pico_sync/lock_core.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.c.obj

P_/pico-sdk/src/common/pico_sync/lock_core.i: P_/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_sync/lock_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.c.i

P_/pico-sdk/src/common/pico_sync/lock_core.s: P_/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_sync/lock_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/lock_core.c.s

P_/pico-sdk/src/common/pico_sync/mutex.obj: P_/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.obj

# target to build an object file
P_/pico-sdk/src/common/pico_sync/mutex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.c.obj

P_/pico-sdk/src/common/pico_sync/mutex.i: P_/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_sync/mutex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.c.i

P_/pico-sdk/src/common/pico_sync/mutex.s: P_/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_sync/mutex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/mutex.c.s

P_/pico-sdk/src/common/pico_sync/sem.obj: P_/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.obj

# target to build an object file
P_/pico-sdk/src/common/pico_sync/sem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.c.obj

P_/pico-sdk/src/common/pico_sync/sem.i: P_/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_sync/sem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.c.i

P_/pico-sdk/src/common/pico_sync/sem.s: P_/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_sync/sem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : P_/pico-sdk/src/common/pico_sync/sem.c.s

P_/pico-sdk/src/common/pico_time/time.obj: P_/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : P_/pico-sdk/src/common/pico_time/time.obj

# target to build an object file
P_/pico-sdk/src/common/pico_time/time.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : P_/pico-sdk/src/common/pico_time/time.c.obj

P_/pico-sdk/src/common/pico_time/time.i: P_/pico-sdk/src/common/pico_time/time.c.i
.PHONY : P_/pico-sdk/src/common/pico_time/time.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_time/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/time.c.i
.PHONY : P_/pico-sdk/src/common/pico_time/time.c.i

P_/pico-sdk/src/common/pico_time/time.s: P_/pico-sdk/src/common/pico_time/time.c.s
.PHONY : P_/pico-sdk/src/common/pico_time/time.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_time/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/time.c.s
.PHONY : P_/pico-sdk/src/common/pico_time/time.c.s

P_/pico-sdk/src/common/pico_time/timeout_helper.obj: P_/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.obj

# target to build an object file
P_/pico-sdk/src/common/pico_time/timeout_helper.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.c.obj

P_/pico-sdk/src/common/pico_time/timeout_helper.i: P_/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_time/timeout_helper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.c.i

P_/pico-sdk/src/common/pico_time/timeout_helper.s: P_/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_time/timeout_helper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : P_/pico-sdk/src/common/pico_time/timeout_helper.c.s

P_/pico-sdk/src/common/pico_util/datetime.obj: P_/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.obj

# target to build an object file
P_/pico-sdk/src/common/pico_util/datetime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.c.obj

P_/pico-sdk/src/common/pico_util/datetime.i: P_/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_util/datetime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.c.i

P_/pico-sdk/src/common/pico_util/datetime.s: P_/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_util/datetime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/datetime.c.s

P_/pico-sdk/src/common/pico_util/pheap.obj: P_/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.obj

# target to build an object file
P_/pico-sdk/src/common/pico_util/pheap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.c.obj

P_/pico-sdk/src/common/pico_util/pheap.i: P_/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_util/pheap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.c.i

P_/pico-sdk/src/common/pico_util/pheap.s: P_/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_util/pheap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/pheap.c.s

P_/pico-sdk/src/common/pico_util/queue.obj: P_/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/queue.obj

# target to build an object file
P_/pico-sdk/src/common/pico_util/queue.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : P_/pico-sdk/src/common/pico_util/queue.c.obj

P_/pico-sdk/src/common/pico_util/queue.i: P_/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/queue.i

# target to preprocess a source file
P_/pico-sdk/src/common/pico_util/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : P_/pico-sdk/src/common/pico_util/queue.c.i

P_/pico-sdk/src/common/pico_util/queue.s: P_/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/queue.s

# target to generate assembly for a file
P_/pico-sdk/src/common/pico_util/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : P_/pico-sdk/src/common/pico_util/queue.c.s

P_/pico-sdk/src/rp2_common/hardware_claim/claim.obj: P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

P_/pico-sdk/src/rp2_common/hardware_claim/claim.i: P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

P_/pico-sdk/src/rp2_common/hardware_claim/claim.s: P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj: P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.i: P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.s: P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

P_/pico-sdk/src/rp2_common/hardware_divider/divider.obj: P_/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_divider/divider.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj: P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.i: P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.s: P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

P_/pico-sdk/src/rp2_common/hardware_irq/irq.obj: P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

P_/pico-sdk/src/rp2_common/hardware_irq/irq.i: P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

P_/pico-sdk/src/rp2_common/hardware_irq/irq.s: P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj: P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

P_/pico-sdk/src/rp2_common/hardware_pll/pll.obj: P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

P_/pico-sdk/src/rp2_common/hardware_pll/pll.i: P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

P_/pico-sdk/src/rp2_common/hardware_pll/pll.s: P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

P_/pico-sdk/src/rp2_common/hardware_sync/sync.obj: P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

P_/pico-sdk/src/rp2_common/hardware_sync/sync.i: P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

P_/pico-sdk/src/rp2_common/hardware_sync/sync.s: P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

P_/pico-sdk/src/rp2_common/hardware_timer/timer.obj: P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

P_/pico-sdk/src/rp2_common/hardware_timer/timer.i: P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

P_/pico-sdk/src/rp2_common/hardware_timer/timer.s: P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

P_/pico-sdk/src/rp2_common/hardware_uart/uart.obj: P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

P_/pico-sdk/src/rp2_common/hardware_uart/uart.i: P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

P_/pico-sdk/src/rp2_common/hardware_uart/uart.s: P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj: P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.i: P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.s: P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj: P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i: P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s: P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj: P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.i: P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.s: P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj: P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj: P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i: P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s: P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

P_/pico-sdk/src/rp2_common/pico_divider/divider.obj: P_/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_divider/divider.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj: P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj: P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.i: P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.s: P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

P_/pico-sdk/src/rp2_common/pico_double/double_math.obj: P_/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_double/double_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

P_/pico-sdk/src/rp2_common/pico_double/double_math.i: P_/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_double/double_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.c.i

P_/pico-sdk/src/rp2_common/pico_double/double_math.s: P_/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_double/double_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_math.c.s

P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj: P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj: P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj: P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.i: P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.s: P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

P_/pico-sdk/src/rp2_common/pico_float/float_math.obj: P_/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_float/float_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

P_/pico-sdk/src/rp2_common/pico_float/float_math.i: P_/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_float/float_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.c.i

P_/pico-sdk/src/rp2_common/pico_float/float_math.s: P_/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_float/float_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_math.c.s

P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj: P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj: P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj: P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i: P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s: P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj: P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

P_/pico-sdk/src/rp2_common/pico_platform/platform.obj: P_/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_platform/platform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

P_/pico-sdk/src/rp2_common/pico_platform/platform.i: P_/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_platform/platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.c.i

P_/pico-sdk/src/rp2_common/pico_platform/platform.s: P_/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_platform/platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_platform/platform.c.s

P_/pico-sdk/src/rp2_common/pico_printf/printf.obj: P_/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_printf/printf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

P_/pico-sdk/src/rp2_common/pico_printf/printf.i: P_/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_printf/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.c.i

P_/pico-sdk/src/rp2_common/pico_printf/printf.s: P_/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_printf/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_printf/printf.c.s

P_/pico-sdk/src/rp2_common/pico_runtime/runtime.obj: P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

P_/pico-sdk/src/rp2_common/pico_runtime/runtime.i: P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

P_/pico-sdk/src/rp2_common/pico_runtime/runtime.s: P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj: P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i: P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s: P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj: P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj: P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i: P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s: P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

P_/pico-sdk/src/rp2_common/pico_stdio/stdio.obj: P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

P_/pico-sdk/src/rp2_common/pico_stdio/stdio.i: P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

P_/pico-sdk/src/rp2_common/pico_stdio/stdio.s: P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj: P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i: P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s: P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj: P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj

# target to build an object file
P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i: P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i

# target to preprocess a source file
P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s: P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s

# target to generate assembly for a file
P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Button.dir\build.make CMakeFiles/Button.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ELF2UF2Build
	@echo ... bs2_default_bin
	@echo ... bs2_default_padded_checksummed_asm
	@echo ... Button
	@echo ... bs2_default
	@echo ... P_/pico-sdk/src/common/pico_sync/critical_section.obj
	@echo ... P_/pico-sdk/src/common/pico_sync/critical_section.i
	@echo ... P_/pico-sdk/src/common/pico_sync/critical_section.s
	@echo ... P_/pico-sdk/src/common/pico_sync/lock_core.obj
	@echo ... P_/pico-sdk/src/common/pico_sync/lock_core.i
	@echo ... P_/pico-sdk/src/common/pico_sync/lock_core.s
	@echo ... P_/pico-sdk/src/common/pico_sync/mutex.obj
	@echo ... P_/pico-sdk/src/common/pico_sync/mutex.i
	@echo ... P_/pico-sdk/src/common/pico_sync/mutex.s
	@echo ... P_/pico-sdk/src/common/pico_sync/sem.obj
	@echo ... P_/pico-sdk/src/common/pico_sync/sem.i
	@echo ... P_/pico-sdk/src/common/pico_sync/sem.s
	@echo ... P_/pico-sdk/src/common/pico_time/time.obj
	@echo ... P_/pico-sdk/src/common/pico_time/time.i
	@echo ... P_/pico-sdk/src/common/pico_time/time.s
	@echo ... P_/pico-sdk/src/common/pico_time/timeout_helper.obj
	@echo ... P_/pico-sdk/src/common/pico_time/timeout_helper.i
	@echo ... P_/pico-sdk/src/common/pico_time/timeout_helper.s
	@echo ... P_/pico-sdk/src/common/pico_util/datetime.obj
	@echo ... P_/pico-sdk/src/common/pico_util/datetime.i
	@echo ... P_/pico-sdk/src/common/pico_util/datetime.s
	@echo ... P_/pico-sdk/src/common/pico_util/pheap.obj
	@echo ... P_/pico-sdk/src/common/pico_util/pheap.i
	@echo ... P_/pico-sdk/src/common/pico_util/pheap.s
	@echo ... P_/pico-sdk/src/common/pico_util/queue.obj
	@echo ... P_/pico-sdk/src/common/pico_util/queue.i
	@echo ... P_/pico-sdk/src/common/pico_util/queue.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_claim/claim.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_claim/claim.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_claim/claim.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_clocks/clocks.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_divider/divider.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_gpio/gpio.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_irq/irq.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_irq/irq.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_irq/irq.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_pll/pll.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_pll/pll.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_pll/pll.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_sync/sync.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_sync/sync.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_sync/sync.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_timer/timer.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_timer/timer.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_timer/timer.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_uart/uart.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_uart/uart.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_uart/uart.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_vreg/vreg.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s
	@echo ... P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj
	@echo ... P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.i
	@echo ... P_/pico-sdk/src/rp2_common/hardware_xosc/xosc.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_divider/divider.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_init_rom.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_math.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_math.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_math.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_init_rom.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_math.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_math.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_math.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_platform/platform.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_platform/platform.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_platform/platform.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_printf/printf.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_printf/printf.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_printf/printf.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_runtime/runtime.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_runtime/runtime.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_runtime/runtime.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio/stdio.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio/stdio.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio/stdio.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i
	@echo ... P_/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

